Updating validation

diff --git a/files/backup b/files/backup
--- a/files/backup
+++ b/files/backup
@@ -2,6 +2,12 @@
 
 source settings
 
+mysql ${MYSQL_OPTS} -e "USE ${MYSQL_DATABASE}"
+if [ $? != 0 ]; then
+    printf "%s\n" "${red}ERROR: Database ${MYSQL_DATABASE} does not exist.${end}"
+    exit 1
+fi
+
 cd ${WORK_DIR}
 
 output_file="${MYSQL_DATABASE}-$(date "+%Y%m%d%H%M%S").sql"
